<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="8.0.16" />
    <PackageReference Include="Swashbuckle.AspNetCore" Version="7.3.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\UsuarioApi.Business\UsuarioApi.Business.csproj" />
    <ProjectReference Include="..\UsuarioApi.DataAcces\UsuarioApi.DataAcces.csproj" />
    <ProjectReference Include="..\UsuarioApi.Models\UsuarioApi.Models.csproj" />
  </ItemGroup>

</Project>
